using GuitarResourcesTui.Triads;
using System.Diagnostics;
using System.Net;
using System.Text;

namespace GuitarResourcesTui.Tui.Printing;

internal static class TriadSongLookupGuidePrinter
{
    private static readonly IReadOnlyList<GuitarString> Tuning =
    [
        new("E (1st)", 4),
        new("B", 11),
        new("G", 7),
        new("D", 2),
        new("A", 9),
        new("E (6th)", 4)
    ];

    private static readonly IReadOnlyList<ChordShortcut> ChordShortcuts =
    [
        new("major", "R 3 5", "major triad", "plain major chord"),
        new("m", "R b3 5", "minor triad", "lower the 3 in the matching major grip by one fret"),
        new("sus4", "R 4 5", "major triad with 3 raised to 4", "good folk, rock, and suspended color"),
        new("dim", "R b3 b5", "minor triad with 5 lowered", "also the color triad inside many dominant 7 chords"),
        new("aug", "R 3 #5", "major triad with 5 raised", "tense passing sound"),
        new("maj7", "R 3 5 7", "major triad + 7", "or play the minor triad from the 3"),
        new("7", "R 3 5 b7", "major triad + b7", "or play the diminished triad from the 3"),
        new("m7", "R b3 5 b7", "minor triad + b7", "or play the major triad from the b3"),
        new("m7b5", "R b3 b5 b7", "diminished triad + b7", "or play the minor triad from the b3"),
        new("6", "R 3 5 6", "major triad + 6", "or play the minor triad from the 6"),
        new("m6", "R b3 5 6", "minor triad + 6", "or play the diminished triad from the 6")
    ];

    public static string Print(TriadInversionLibrary triads)
    {
        var filePath = Path.Combine(Path.GetTempPath(), "guitar-tui-triad-song-chord-lookup-guide.html");
        File.WriteAllText(filePath, BuildHtml(triads));
        Open(filePath);
        return filePath;
    }

    private static void Open(string filePath)
    {
        if (OperatingSystem.IsMacOS())
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = "open",
                UseShellExecute = false,
                CreateNoWindow = true,
                ArgumentList = { filePath }
            });
        }
        else
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = filePath,
                UseShellExecute = true
            });
        }
    }

    private static string BuildHtml(TriadInversionLibrary triads)
    {
        var builder = StartHtml("Triad song-chord lookup guide");
        builder.AppendLine("<h1>Triad song-chord lookup guide</h1>");
        builder.AppendLine($"<div class=\"subtitle\">Generated by guitar-tui on {DateTime.Now:yyyy-MM-dd HH:mm}</div>");
        builder.AppendLine("<p class=\"hint\"><b>Fast use:</b> read the song chord, choose the triad core, find that root in the lookup table, then pick a string set near your hand. For E7, Am, G: use E major triads plus D as b7, A minor triads, and G major triads.</p>");

        AppendNoteMap(builder);
        AppendHowToRead(builder);
        AppendChordShortcutTable(builder);
        AppendUpperTriadTable(builder);
        AppendTriadLookup(builder, triads, ChordQuality.Major);
        AppendTriadLookup(builder, triads, ChordQuality.Minor);
        AppendModificationCheats(builder);

        builder.AppendLine("</body>");
        builder.AppendLine("</html>");
        return builder.ToString();
    }

    private static StringBuilder StartHtml(string title)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!doctype html>");
        builder.AppendLine("<html lang=\"en\">");
        builder.AppendLine("<head>");
        builder.AppendLine("<meta charset=\"utf-8\">");
        builder.AppendLine($"<title>{Html(title)}</title>");
        builder.AppendLine("""
<style>
@page { size: A4; margin: 10mm; }
body { color: #111; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; font-size: 10px; line-height: 1.25; margin: 18px; }
h1 { font-size: 23px; margin: 0 0 3px; }
h2 { border-bottom: 1px solid #888; font-size: 14px; margin: 16px 0 8px; padding-bottom: 3px; }
h3 { font-size: 11px; margin: 8px 0 4px; }
.subtitle, .hint { color: #555; font-size: 11px; margin: 0 0 10px; max-width: 980px; }
.page { break-before: page; page-break-before: always; }
.grid-2 { display: grid; gap: 10px; grid-template-columns: 1fr 1fr; }
table { border-collapse: collapse; width: 100%; }
th { background: #ece7d6; color: #333; font-weight: 700; }
td, th { border: 1px solid #777; padding: 3px 4px; text-align: left; vertical-align: top; }
.note-map td, .note-map th { text-align: center; }
.string { background: #f7f7f7; font-weight: 700; white-space: nowrap; }
.root { background: #c8f7c5; font-weight: 800; }
.quality { font-weight: 800; white-space: nowrap; }
.formula { white-space: nowrap; }
.lookup td { font-size: 9px; }
.lookup .root-cell { background: #f7f7f7; font-size: 11px; font-weight: 800; text-align: center; vertical-align: middle; width: 34px; }
.grip { display: block; white-space: nowrap; }
.inv { color: #555; display: inline-block; font-weight: 700; width: 12px; }
.functions { color: #555; display: inline-block; margin-left: 4px; }
.notes { color: #444; font-size: 9px; margin-top: 2px; }
.small { color: #555; font-size: 9px; }
.example { background: #edf7ff; border-left: 3px solid #4087b8; margin: 8px 0 12px; padding: 6px 8px; }
ul { margin: 5px 0 0 16px; padding: 0; }
li { margin-bottom: 3px; }
section { break-inside: avoid; page-break-inside: avoid; }
thead { display: table-header-group; }
@media print {
  body { margin: 0; }
  .page { break-before: page; page-break-before: always; }
}
</style>
<script>
window.addEventListener("load", () => setTimeout(() => window.print(), 250));
</script>
""");
        builder.AppendLine("</head>");
        builder.AppendLine("<body>");
        return builder;
    }

    private static void AppendNoteMap(StringBuilder builder)
    {
        builder.AppendLine("<section>");
        builder.AppendLine("<h2>Fretboard note map, frets 0-12</h2>");
        builder.AppendLine("<table class=\"note-map\"><thead><tr><th>String</th>");
        for (var fret = 0; fret <= 12; fret++)
        {
            builder.AppendLine($"<th>{fret}</th>");
        }
        builder.AppendLine("</tr></thead><tbody>");

        foreach (var guitarString in Tuning)
        {
            builder.AppendLine("<tr>");
            builder.AppendLine($"<td class=\"string\">{Html(guitarString.Name)}</td>");
            for (var fret = 0; fret <= 12; fret++)
            {
                var note = MusicTheory.NameFor(guitarString.PitchClass + fret);
                builder.AppendLine($"<td{(fret == 0 || fret == 12 ? " class=\"root\"" : string.Empty)}>{Html(note)}</td>");
            }
            builder.AppendLine("</tr>");
        }

        builder.AppendLine("</tbody></table>");
        builder.AppendLine("</section>");
    }

    private static void AppendHowToRead(StringBuilder builder)
    {
        builder.AppendLine("<section>");
        builder.AppendLine("<h2>How to read the grip tables</h2>");
        builder.AppendLine("<div class=\"grid-2\">");
        builder.AppendLine("<div><h3>Grip format</h3><p class=\"hint\">Each cell shows frets on that string set from high string to low string. On the E B G set, <b>0-0-1</b> means high E open, B open, G fret 1. The small label after it shows the chord tones on those same strings.</p></div>");
        builder.AppendLine("<div><h3>Song-chord method</h3><p class=\"hint\">For plain triad comping, reduce the chord symbol to its core: E7 uses E major, Am uses A minor, G uses G major. Add or aim for the 7th/6th color note when you want the fuller chord sound.</p></div>");
        builder.AppendLine("</div>");
        builder.AppendLine("<div class=\"example\"><b>Example:</b> E7, Am, G. Look up E in Fast major triads, A in Fast minor triads, and G in Fast major triads. For the E7 color, D is the b7; add it nearby or use G# diminished as the upper triad color.</div>");
        builder.AppendLine("<div class=\"example\"><b>Inversions:</b> root position has R as the lowest note, first inversion has 3 or b3 as the lowest note, and second inversion has 5 as the lowest note. The grip table lists strings high-to-low, so the last interval in each small layout is the bass note that names the inversion.</div>");
        builder.AppendLine("</section>");
    }

    private static void AppendChordShortcutTable(StringBuilder builder)
    {
        builder.AppendLine("<section>");
        builder.AppendLine("<h2>Chord symbol shortcuts</h2>");
        builder.AppendLine("<table><thead><tr><th>Symbol</th><th>Formula</th><th>Triad core</th><th>Fast idea</th></tr></thead><tbody>");
        foreach (var shortcut in ChordShortcuts)
        {
            builder.AppendLine("<tr>");
            builder.AppendLine($"<td class=\"quality\">{Html(shortcut.Symbol)}</td>");
            builder.AppendLine($"<td class=\"formula\">{Html(shortcut.Formula)}</td>");
            builder.AppendLine($"<td>{Html(shortcut.TriadCore)}</td>");
            builder.AppendLine($"<td>{Html(shortcut.FastIdea)}</td>");
            builder.AppendLine("</tr>");
        }
        builder.AppendLine("</tbody></table>");
        builder.AppendLine("</section>");
    }

    private static void AppendUpperTriadTable(StringBuilder builder)
    {
        builder.AppendLine("<section>");
        builder.AppendLine("<h2>Upper triad color shortcuts</h2>");
        builder.AppendLine("<p class=\"hint\">Use the left triad for the direct chord sound. Use the right triad when the band or bass is covering the root and you want stronger 6th/7th color.</p>");
        builder.AppendLine("<table><thead><tr><th>Root</th><th>maj7</th><th>7</th><th>m7</th><th>m7b5</th><th>6</th><th>m6</th></tr></thead><tbody>");

        foreach (var root in MusicTheory.ChromaticRoots)
        {
            builder.AppendLine("<tr>");
            builder.AppendLine($"<td class=\"root-cell\">{Html(root)}</td>");
            builder.AppendLine($"<td>{Html(root)} major or {Html(Name(root, "3"))} minor<div class=\"notes\">{Html(Notes(root, ["R", "3", "5", "7"]))}</div></td>");
            builder.AppendLine($"<td>{Html(root)} major or {Html(Name(root, "3"))} dim<div class=\"notes\">{Html(Notes(root, ["R", "3", "5", "b7"]))}</div></td>");
            builder.AppendLine($"<td>{Html(root)} minor or {Html(Name(root, "b3"))} major<div class=\"notes\">{Html(Notes(root, ["R", "b3", "5", "b7"]))}</div></td>");
            builder.AppendLine($"<td>{Html(root)} dim or {Html(Name(root, "b3"))} minor<div class=\"notes\">{Html(Notes(root, ["R", "b3", "b5", "b7"]))}</div></td>");
            builder.AppendLine($"<td>{Html(root)} major or {Html(Name(root, "6"))} minor<div class=\"notes\">{Html(Notes(root, ["R", "3", "5", "6"]))}</div></td>");
            builder.AppendLine($"<td>{Html(root)} minor or {Html(Name(root, "6"))} dim<div class=\"notes\">{Html(Notes(root, ["R", "b3", "5", "6"]))}</div></td>");
            builder.AppendLine("</tr>");
        }

        builder.AppendLine("</tbody></table>");
        builder.AppendLine("</section>");
    }

    private static void AppendTriadLookup(StringBuilder builder, TriadInversionLibrary triads, ChordQuality quality)
    {
        builder.AppendLine($"<section class=\"page\">");
        builder.AppendLine($"<h2>Fast {Html(quality.ToString().ToLowerInvariant())} triad lookup</h2>");
        builder.AppendLine($"<p class=\"hint\">Formula: {Html(quality == ChordQuality.Major ? "R 3 5" : "R b3 5")}. Frets are listed high-to-low inside each string set.</p>");
        builder.AppendLine("<table class=\"lookup\"><thead><tr><th>Root</th><th>Notes</th><th>E B G</th><th>B G D</th><th>G D A</th><th>D A E</th></tr></thead><tbody>");

        foreach (var root in MusicTheory.ChromaticRoots)
        {
            var groupings = triads.GetTriadInversions(root, quality).ToDictionary(grouping => grouping.Name);
            builder.AppendLine("<tr>");
            builder.AppendLine($"<td class=\"root-cell\">{Html(root)}</td>");
            builder.AppendLine($"<td>{Html(TriadNotes(root, quality))}</td>");
            foreach (var groupingName in new[] { "E B G", "B G D", "G D A", "D A E" })
            {
                builder.AppendLine($"<td>{GripText(groupings[groupingName])}</td>");
            }
            builder.AppendLine("</tr>");
        }

        builder.AppendLine("</tbody></table>");
        builder.AppendLine("</section>");
    }

    private static void AppendModificationCheats(StringBuilder builder)
    {
        builder.AppendLine("<section class=\"page\">");
        builder.AppendLine("<h2>Shape modification cheats</h2>");
        builder.AppendLine("<div class=\"grid-2\">");
        builder.AppendLine("<div><h3>Start from major</h3><ul>");
        builder.AppendLine("<li><b>minor</b>: lower the 3 one fret.</li>");
        builder.AppendLine("<li><b>sus4</b>: raise the 3 one fret.</li>");
        builder.AppendLine("<li><b>augmented</b>: raise the 5 one fret.</li>");
        builder.AppendLine("<li><b>major 7</b>: add 7 one fret below the root, or replace the root with 7 for a rootless color.</li>");
        builder.AppendLine("<li><b>dominant 7</b>: add b7 two frets below the root, or replace the root with b7 for a rootless color.</li>");
        builder.AppendLine("</ul></div>");
        builder.AppendLine("<div><h3>Start from minor</h3><ul>");
        builder.AppendLine("<li><b>diminished</b>: lower the 5 one fret.</li>");
        builder.AppendLine("<li><b>minor 7</b>: add b7 two frets below the root.</li>");
        builder.AppendLine("<li><b>m7b5</b>: minor 7 with the 5 lowered one fret.</li>");
        builder.AppendLine("<li><b>m6</b>: add 6 three frets below the root or nine frets above it.</li>");
        builder.AppendLine("<li><b>add9</b>: keep the triad and add 9 two frets above the root.</li>");
        builder.AppendLine("</ul></div>");
        builder.AppendLine("</div>");
        builder.AppendLine("<h2>Practice loop</h2>");
        builder.AppendLine("<ol>");
        builder.AppendLine("<li>Pick a song progression and reduce every chord to major, minor, diminished, or a color shortcut.</li>");
        builder.AppendLine("<li>Choose one string set and play the nearest inversion for each chord.</li>");
        builder.AppendLine("<li>Repeat on another string set, keeping the movement as small as possible.</li>");
        builder.AppendLine("<li>Add one color note for every 7, maj7, m7, 6, or m6 chord after the triads feel automatic.</li>");
        builder.AppendLine("</ol>");
        builder.AppendLine("</section>");
    }

    private static string GripText(TriadGroupingResult grouping)
    {
        var labels = new Dictionary<string, string>
        {
            ["Root"] = "R",
            ["1st inv"] = "1",
            ["2nd inv"] = "2"
        };

        return string.Join(
            string.Empty,
            grouping.Shapes.Select(shape =>
            {
                var frets = shape.Diagram.Positions
                    .OrderBy(position => position.StringIndex)
                    .Select(position => position.Fret.ToString());
                var functions = shape.Diagram.Positions
                    .OrderBy(position => position.StringIndex)
                    .Select(position => position.Label);
                var label = labels.GetValueOrDefault(shape.InversionName, shape.InversionName);
                return $"<span class=\"grip\"><span class=\"inv\">{Html(label)}</span>{Html(string.Join("-", frets))}<span class=\"functions\">{Html(string.Join("-", functions))}</span></span>";
            }));
    }

    private static string TriadNotes(string root, ChordQuality quality)
    {
        var intervals = quality == ChordQuality.Major ? new[] { "R", "3", "5" } : ["R", "b3", "5"];
        return Notes(root, intervals);
    }

    private static string Notes(string root, IReadOnlyList<string> intervals)
    {
        return string.Join(" ", intervals.Select(interval => Name(root, interval)));
    }

    private static string Name(string root, string interval) => MusicTheory.NameForInterval(root, interval);

    private static string Html(string value) => WebUtility.HtmlEncode(value);

    private sealed record GuitarString(string Name, int PitchClass);

    private sealed record ChordShortcut(string Symbol, string Formula, string TriadCore, string FastIdea);
}
